### ISSUE TITLE
`shinytest` ideas

### ISSUE THREAD

**Issue by marklhc** [claycantrell/PartInvShinyUI#5]
1. A success trial:
    - lambda_r = .9, .8, .8, .5
    - tau_r =

**Comment by YichiZhang2024** [comment]
1. Success trial:
    - lambda_r = 0.677, 0.746, 0.768, 0.664
    - tau_r = 2.275, 2.928, 3.437, 3.095
    - tau_f = 2.275, 2.928, 3.013, 3.095
    - diag(Theta_r) = 0.744, 1.061, 0.899, 0.638
    - kappa_r = -0.032
    - kappa_f = 0
    - phi_r = 1.032
    - phi_f = 1
    - propsel = 0.25
2. Theta matrix needs to be uploaded
    - diag(Theta_r) = 0.744, 1.061, 0.899, 0.638; Theta_r[1,4] = Theta_r[4, 1] = 0.083
3. Parameter with different dimensions
    1) lambda, tau, and diag(Theta) should be equal
    2) kappa and phi should both be a single number
4. Parameter missing
    1) lambda_r, tau_r, Theta_r, kappa_r, phi_r should not be missing
5. Parameter Values 
    1) Reference group and focal group cannot have the same values for all parameters (strict invariance)?
    2) diagonals of Theta_r and Theta_f should be positive numbers
    3) mixing proportion should be positive and less than 1
6. Need to check reset inputs button
7. Use cutoff score instead of selection proportion
